site_name: My Tech Notebook
site_url: https://wiki.deimos.fr
repo_url: https://github.com/deimosfr/mytechnotebook
edit_uri: edit/main/docs/
hooks:
  - overrides/.hooks/meta_slugs.py
theme:
  icon:
    repo: fontawesome/brands/git-alt
  font:
    text: Lato
  features:
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.share
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.tabs.link
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
extra:
  analytics:
    provider: google
    property: G-4EGFC89L7K
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/file-icons.js
plugins:
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      exclude:
        - index.md
        - "**/index.md"
      type: date
      # Enhanced date processing options
      include_relative_dates: true
      date_format_in_metadata: true
      creation_date_field_name: date
      update_date_field_name: lastmod
  - search
  - offline
  # icons in nav menu
  - section-index
  - minify:
      minify_html: true
  - macros:
      on_undefined: strict
      on_error_fail: !ENV [MACRO_ERROR_FAIL, false]
markdown_extensions:
  # code highlight
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  # callouts
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # grids
  - attr_list
  - md_in_html
  # automatic link
  - pymdownx.magiclink
  # emoji + icons
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # tables
  - tables